### ISSUE TITLE
auto doesn't work when the page is back by history.go(-1)

### ISSUE THREAD

**Issue by Jack54s** [lyfeyaj/swipe#105]
When I go into a page from the page with Swipe and go back, the swipe's 'auto' property won't work. It will be okay if you touchmove it.

Forgive my poor English.

**Comment by loup-brun** [comment]
Hi! If you're running `history.go`, I believe you are running a SPA or a webapp which **doesn't reload the page** – therefore, Swipe is not reloaded, and thus doesn't restart.

## My suggestion 

_I'm assuming a lot about the context here, since you didn't provide much information._

### Pieces of the puzzle

* You should **listen** for a `popstate` event (basically, an event that fires when you do `history.go`).
* From the [Swipe API](https://github.com/lyfeyaj/swipe#api), you can use the `.restart()` method, which will reload your Swipe instance with your config.

### Example

```js
// Create your swipe instance
window.mySwipe = new Swipe(/* your elem, config */)

// Add event listener to restart Swipe on 'popstate' (history) change
window.addEventListener('popstate', function (event) {
  window.mySwipe.restart();
}, false)
```

**Comment by Jack54s** [comment]
Thanks. It's helpful.
