### ISSUE TITLE
UI glitch on resizing - other slides are visible for a few moments before the slider rebuild its layout

### ISSUE THREAD

**Issue by balazsnemeth** [lyfeyaj/swipe#112]
Hi,

Thank you for building this awesome slider component!

I have a Ui glitch I want to discuss with you.

How to reproduce:
Go to the example page: https://swipe.js.org, try to resize the window very rapidly. You can see multiple slides are appearing during the resizing, but after a very short amount of time the slider recover/rebuild the layout.
Here is a video about it, I recommend to see frame by frame to make sure you can catch it:
https://www.dropbox.com/s/1ze6mzi7w7thrtn/resizing_bug.mov?dl=0

Is it possible to avoid this UI glitch? On my project, I have a larger slider with more complex slides, so this is resulting slide overlapping and more well-marked issue.

Any suggestion how to avoid this?

**Comment by loup-brun** [comment]
Before talking about a “fix”, are you sure this is actually relevant (are your users going to resize the window super quickly? are the users going to care/notice?).

If you can post an example (screen recording or jsbin/codepen link) for your specific example, it could help understand why this issue is relevant to you.

At a first glance, I would not call this a _bug_ – it's a really edgy-edgy use case.

## Workarounds

### Solution 1 : Listen for window resize
 
If you wish that the slides do not appear on window `resize`, you can add an event listener which adds a class to the document/body, enabling you to **hide** the slides with CSS; once window resize is done, remove the class.

```css
/* apply the is-resizing class on <html> or <body> element */
.is-resizing .swipe-wrap > div {
  visibility: hidden;
}
```

I put together a small [Codepen demo](https://codepen.io/loupbrun/full/MWWbgBZ) with some javascript details – try it out yourself.

**Comment by balazsnemeth** [comment]
Thank you for your demo, works like a charm!
