### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by krem06** [lyfeyaj/swipe#28]
Hi there,

I am trying to use the plugin in a webapp but get stuck on how to handle dynamic content... I checked the original project and there are some suggestions but nothing buit-in, do you have a best practice to load new slides dynamically in the list ?

Thank you ;)

**Comment by axelson** [comment]
My PR includes basic instructions for this: https://github.com/lyfeyaj/swipe/issues/61

**Comment by loup-brun** [comment]
Hmm... Dynamic content can be achieved by first destroying the existing Swipe instance and then creating a new one after dynamically playing with content of the slider.

Basically,

```js
window.mySwipe1 = new Swipe(elem, options);
mySwipe1.kill();
/* dynamically add slides HERE */
window.mySwipe2 = new Swipe(elem, options});

// repeat this cycle every time slides are added, ideally erasing each Swipe instance after `kill()`
```

I acknowledge, this creates a lot of overhead.

@axelson In your PR, you're making an **exception** for the setup behavior only for the `startSlide` option. I would suggest making it possible to pass an (optional) `options` parameter to the `setup()` method, which could override the initial configuration (passed when creating a Swipe instance). This could be very helpful, since it could be desirable to alter some options over time without having to create a new Swipe instance every time.

I think extending (generalizing) this way of altering the configuration to all options is a better design approach (rather than relying on exceptions). Please feel free to share your thoughts! :smile:

**Comment by axelson** [comment]
Yeah I think that makes sense, just wasn't sure how much work it would be to set all the options again. But perhaps if we extracted it to a new method, something like `configureOptions` then that could be used both in the `setup` case as well as the `new` case.

**Comment by loup-brun** [comment]
Yes, this `configureOptions` could be abstracted to a private (internal) method. However, I'm afraid such a design change will be a good deal of work considering the way Swipe is already built: the configuration options seem to be pretty much spread out accross the different parts of Swipe. I'll have to look into the code and see if it is actually possible to do this in Swipe!
