### ISSUE TITLE
Probleme with auto restart prop

### ISSUE THREAD

**Issue by colir** [lyfeyaj/swipe#6]
Hi.
i've a little probleme with swipe 2 and the autoRestart param.
If  i dont set it to false and i and i click once on a "next" button , my swip gallery fall in a loop :
It didn't forward by just one step...

so i must write
autoRestart : false

thanks.

**Comment by lyfeyaj** [comment]
Hi, I can't replicate the issue you reported by this example: <http://lyfeyaj.github.io/swipe/>
Can you provide more information to help me to identify the problem?

**Comment by SirMojo** [comment]
Hi, same problem here. It happens when you set the options `auto:0` and `draggable:true`
Looking at your code the line 66 is the problem, you set the default autoReset value to true if the option isn't initially set.

`options.autoRestart = options.autoRestart !== undefined ? options.autoRestart : true;`

If you change the default value to `false` it should work. Or is there some other reason why you set this to true?

**Comment by lyfeyaj** [comment]
Hi @SirMojo, @colir 
`autoStart` option is used to work with `auto` option, by default behavior when you set the `auto` with a number, lets say: `2000`, then when you click `prev` or `next` the carousel will stop looping, but with `autoRestart` is on, it will continue looping. That's why I set `autoRestart` to true.
Base on you guys' requests, I will set this `autoRestart` option default to false and publish a new version.

**Comment by lyfeyaj** [comment]
Fixed in 2.0.7

**Comment by colir** [comment]
thanks. i will test it.
