### ISSUE TITLE
auto not work when touchstart event trigger

### ISSUE THREAD

**Issue by cycgit** [lyfeyaj/swipe#70]

**Comment by loup-brun** [comment]
Hi,
This is the default behavior in Swipe. Auto stops as soon as the user interacts with the slider. You can change this behavior in the configuration by setting the `autoRestart` value to `true` (see the **Config options** in the [README](https://github.com/lyfeyaj/swipe/blob/master/README.md#config-options)).

I'll close this right away since it doesn't actually seem to be a bug. Let me know if this doesn't answer your question of if you need further help solving your issue.
